### NUMPY
- Numpy stands for numerical python
- Numpy is a python library used for worling with arrays

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [6]:
# create 1D array
a1 = np.array([1,2,3,4,5])
print(a1)
print(a1.ndim)

[1 2 3 4 5]
1


In [16]:
# create 2D array
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(a2)
print(a2.ndim)
print(a2.shape)
type(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
2
(5, 3)


numpy.ndarray

In [25]:
# create 3D array
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]])
print(a3)
print(a3.ndim)
print(a3.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]
3
(1, 6, 3)


In [26]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.itemsize)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3
(2, 3, 3)
18
4


In [28]:
# create 4D array
a4 = np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]]])
print(a4)
print(a4.ndim)
print(a4.shape)
print(a3.size)
print(a3.itemsize)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]
   [13 14 15]]]]
4
(1, 1, 5, 3)
18
4


In [29]:
a4 = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(a4)
print(a4.ndim)
print(a4.shape)
print(a3.size)
print(a3.itemsize)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
4
(1, 2, 2, 3)
18
4


### Creating

In [30]:
a1 = np.array(range(10))
print(a1)
print(a1.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [31]:
a1 = np.array(range(10)).reshape(5,2)
print(a1)
print(a1.ndim)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
2


In [35]:
a1 = np.array(range(10)).reshape(1,5,2)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
3
(1, 5, 2)


In [34]:
a1 = np.array(range(10)).reshape(1,2,5)
print(a1)
print(a1.ndim)

[[[0 1 2 3 4]
  [5 6 7 8 9]]]
3


In [38]:
a1 = np.array(range(10)).reshape(2,5,1)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]
3
(2, 5, 1)


In [39]:
a1 = np.array(range(10)).reshape(2,1,5)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
3
(2, 1, 5)


In [43]:
a1 = np.array(range(10,40)).reshape(1,10,3)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[10 11 12]
  [13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]
  [37 38 39]]]
3
(1, 10, 3)


In [44]:
a1 = np.array(range(10,40)).reshape(1,3,10)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]]
3
(1, 3, 10)


In [46]:
# with 5 rows n 6 colums
a1 = np.array(range(10,40)).reshape(1,5,6)
print(a1)
print(a1.ndim)
print(a1.shape)
# with 6 rows n 5 colums
a1 = np.array(range(10,40)).reshape(1,6,5)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[10 11 12 13 14 15]
  [16 17 18 19 20 21]
  [22 23 24 25 26 27]
  [28 29 30 31 32 33]
  [34 35 36 37 38 39]]]
3
(1, 5, 6)
[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]
3
(1, 6, 5)


In [49]:
# with 2 layers----> 3 rows each n 5 columns
a1 = np.array(range(10,40)).reshape(2,3,5)
print(a1)
print(a1.ndim)
print(a1.shape)
# with 2 layers----> 5 rows each n 3 columns
a1 = np.array(range(10,40)).reshape(2,5,3)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]
3
(2, 3, 5)
[[[10 11 12]
  [13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]
  [37 38 39]]]
3
(2, 5, 3)


### Creating an array using arrange()
* np.arrange(start,end,step).reshape()

In [103]:
a2 = np.arange(10,30).reshape(5,4)
print(a2)
print(a2.ndim)
print(a2.size)
print(a2.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
2
20
(5, 4)


In [104]:
a2 = np.arange(10,30).reshape(1,5,4)
print(a2)
print(a2.ndim)
print(a2.size)
print(a2.shape)

[[[10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]
  [26 27 28 29]]]
3
20
(1, 5, 4)


In [105]:
a2 = np.arange(10,30).reshape(2,5,2)
print(a2)
print(a2.ndim)
print(a2.size)
print(a2.shape)

[[[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
3
20
(2, 5, 2)


In [108]:
a2 = np.arange(10,30).reshape(2,2,5,1)
print(a2)
print(a2.ndim)
print(a2.size)
print(a2.shape)

[[[[10]
   [11]
   [12]
   [13]
   [14]]

  [[15]
   [16]
   [17]
   [18]
   [19]]]


 [[[20]
   [21]
   [22]
   [23]
   [24]]

  [[25]
   [26]
   [27]
   [28]
   [29]]]]
4
20
(2, 2, 5, 1)


### Zeros Matrix

In [64]:
z = np.zeros((5,5))
print(z)
print(z[1][1])
print(type(z[1][1]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
0.0
<class 'numpy.float64'>


In [65]:
z = np.zeros((5,5),dtype=int)
print(z)
print(z[1][1])
print(type(z[1][1]))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
<class 'numpy.int32'>


### Ones Matrix

In [66]:
one = np.ones((4,4),dtype=int)
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [68]:
print(5*one)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [69]:
print(5*one-one)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [75]:
print(10*one-7*one+40*one)

[[43 43 43 43]
 [43 43 43 43]
 [43 43 43 43]
 [43 43 43 43]]


In [77]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [78]:
r = np.random.randint(10)
r

9

In [81]:
r = np.random.randint(10,20,7)
r

array([17, 16, 15, 14, 11, 16, 15])

In [83]:
r = np.random.randint(10,50,10).reshape(2,5)
print(r)

[[20 24 15 37 40]
 [37 14 42 49 28]]


In [84]:
r = np.random.randint(10,50,40).reshape(8,5)
print(r)

[[31 20 11 35 10]
 [28 22 30 36 12]
 [18 13 48 15 47]
 [15 36 33 23 28]
 [43 12 30 49 12]
 [29 10 17 17 35]
 [38 41 22 39 48]
 [48 42 28 15 34]]


In [87]:
r = np.random.randint(10,50,40).reshape(5,8)
print(r)
print(r.ndim)

[[46 20 10 25 25 40 40 11]
 [20 28 45 40 38 44 31 40]
 [29 36 41 17 30 22 10 25]
 [46 17 33 45 16 20 11 25]
 [26 22 22 20 37 15 42 43]]
2


In [88]:
r = np.random.randint(10,50,40).reshape(1,5,8)
print(r)
print(r.ndim)

[[[40 37 49 11 49 18 28 33]
  [41 29 12 32 38 40 44 10]
  [13 30 18 12 23 46 10 24]
  [31 20 29 45 18 15 27 34]
  [21 17 27 20 44 49 23 18]]]
3


In [89]:
r = np.random.randint(10,50,40).reshape(2,5,4)
print(r)
print(r.ndim)

[[[29 36 11 35]
  [10 15 21 38]
  [20 42 13 19]
  [21 24 42 42]
  [47 40 26 26]]

 [[27 10 47 14]
  [12 17 49 21]
  [40 15 19 25]
  [38 18 16 43]
  [38 26 32 39]]]
3


In [90]:
r = np.random.randint(10,50,(4,5))
print(r)
print(r.ndim)

[[44 17 48 20 46]
 [19 25 30 20 28]
 [29 15 21 17 34]
 [29 15 18 13 13]]
2


In [91]:
r = np.random.randint(10,50,(1,4,5))
print(r)
print(r.ndim)

[[[10 45 42 22 31]
  [22 22 11 47 42]
  [28 32 44 37 44]
  [46 39 35 48 17]]]
3


In [92]:
r = np.random.randint(10,50,(2,2,5))
print(r)
print(r.ndim)

[[[31 13 12 20 14]
  [28 41 49 32 38]]

 [[35 39 25 38 19]
  [40 15 49 48 21]]]
3


In [93]:
np.random.random()

0.6511304417803729

In [95]:
np.random.random((5,2))

array([[0.17560691, 0.0132309 ],
       [0.91607341, 0.1099509 ],
       [0.92797271, 0.63749115],
       [0.21968366, 0.34515857],
       [0.84068479, 0.46605754]])

In [96]:
print(np.mean(a1))

24.5


In [97]:
print(np.median(a1))

24.5


In [109]:
print(np.log(1))

0.0


In [99]:
r = np.random.randint(10,40,(6,5))
print(r)
print(r.ndim)

[[29 37 21 39 34]
 [20 17 33 11 12]
 [39 26 28 24 18]
 [34 13 26 14 23]
 [11 29 35 34 39]
 [24 25 18 14 11]]
2
